schema = 3

[mod]
  [mod."github.com/cloudflare/cloudflare-go"]
    version = "v0.90.0"
    hash = "sha256-eYQnomNsNLsZPl+1bNcv4sKJMZmJyhsT08ooLNWa4JQ="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.2"
    hash = "sha256-6fMD2/Rku8HT0zDdeA23pX0YxbohiIOC8OJNYbylJTQ="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-retryablehttp"]
    version = "v0.7.5"
    hash = "sha256-5gar22a9HSIxofYQhEgdoiSRFpX59E4p3qxgWYVY4BY="
  [mod."github.com/miekg/dns"]
    version = "v1.1.58"
    hash = "sha256-UGvyC1Abh2S5VaAUCV9AUuDMrCvpiWQy/UnYM9DfIB8="
  [mod."golang.org/x/mod"]
    version = "v0.14.0"
    hash = "sha256-sx3hWp5l99DBfIrn821ohfoBwvaITSHMWbzPvX0btLM="
  [mod."golang.org/x/net"]
    version = "v0.22.0"
    hash = "sha256-pcefO4noO9I6mATKBWF6shgIjZvFg0kDsV1Jo/NsFns="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."golang.org/x/tools"]
    version = "v0.17.0"
    hash = "sha256-CxuHfKKtUkn3VjA7D9WQjzvV1EUbyI/xMNhb5CxO6IQ="
